config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  get '/profil', to: 'users#edit', as: :profil
  patch '/profil', to: 'users#update'
  get '/users', to: 'users#new'

  resources :users, only: [:new, :create] do
    member do
      get 'confirm'
    end
  end

  #Pets
  resources :pets

  #passwords
  resources :passwords, only: [:new, :create, :edit, :update]

  #sessions
  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :destroy_session

end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  belongs_to :species, counter_cache: true

  validates :name, :gender, :birthday, presence: true
  validates :gender, format: {with: /\A(M|F)\z/}
  validates :avatar_file, presence: true, on: :create

  validate :birthday_not_future

  has_image :avatar

  def age
    if Time.now.year == birthday.year and  Time.now.month == birthday.month
      [Time.now.day - birthday.day,'jour'.pluralize(Time.now.day - birthday.day)].join(' ')
    elsif Time.now.year == birthday.year and Time.now.month != birthday.month
      [Time.now.month - birthday.month,'mois'].join(' ')
    else
      [Time.now.year - birthday.year,'an'.pluralize(Time.now.year - birthday.year)].join(' ')
    end
  end

  def birthday_not_future
    if birthday.present? && birthday.future?
      errors.add(:birthday, 'not in the future')
    end
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = current_user.pets
  end

  def new
    @pet = current_user.pets.new
  end

  def create
    @pet = current_user.pets.new(pet_params)
    if @pet.save
      redirect_to pets_path, success: "Votre animal a bien été ajouté."
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @pet.update(pet_params)
      redirect_to pets_path, success: "Votre animal a bien été mofifié."
    else
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path, success: "Votre animal a bien été supprimé."
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :gender, :birthday, :species_id, :avatar_file)
  end

  def set_pet
    @pet = current_user.pets.find(params[:id])
  end

end

app/views/pets/_form.html.erb
  <%= form_for pet, url: pet.new_record? ? pets_path : pet_path, html: {class: 'form-group'} do |f| %>

    <% if pet.errors.any? %>
        <div class="alert alert-danger">
            <ul>
              <% pet.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
    <% end %>

    <div class="mb-1">
      <%= f.label :name, 'Nom', class: 'form-label' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="mb-1">
      <%= f.label :gender, 'Sexe', class: 'form-label' %>
      <%= f.select :gender, {Male: :M, Femelle: :F}, {}, class: 'form-select' %>
    </div>
    <div class="mb-1">
      <%= f.label :birthday, 'Date de naissance', class: 'form-label' %>
      <%= f.date_field :birthday, class: 'form-control', min: '1900-01-01', max: Time.now %>
    </div>
    <div class="mb-3">
      <%= f.label :species_id, 'Espèce', class: 'form-label' %>
      <%= f.select :species_id, Species.pluck(:name, :id), {}, class: 'form-select' %>
    </div>
    <div class="mb-3">
      <%= f.label :avatar_file, 'Avatar', class: 'form-label' %>
      <%= f.file_field :avatar_file, class: 'form-control' %>
    </div>

    <div class="mb-1">
      <button type="submit" class="btn btn-primary">Enregistrer</button>
    </div>

  <% end %>

app/views/pets/edit.html.erb
<% content_for :content do %>
  <div class="card text-white bg-secondary">
    <h5 class="card-header">Modification <%= @pet.name %></h5>
    <div class="card-body">
      <%= render 'form', pet: @pet %>
    </div>
  </div>
<% end %>

<%= render template: 'layouts/profile' %>

app/views/pets/index.html.erb
<% content_for :tag, :pets %>
<% content_for :content do %>
  <h1>Mes animaux</h1>

  <p class="text-start">
    <a href="<%= new_pet_path %>" class="btn btn-success">Ajouter un animal</a>
  </p>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Avatar</th>
        <th>Nom</th>
        <th>Sexe</th>
        <th>Age</th>
        <th>Espèce</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @pets.each do |pet| %>
        <tr>
          <td><%= image_tag pet.avatar_url %></td>
          <td><%= pet.name %></td>
          <td><%= pet.gender %></td>
          <td><%= pet.age %> </td>
          <td><%= pet.species.name %></td>
          <td>
            <%= link_to('Voir', pet, class: "btn btn-primary btn-sm") %>
            <%= link_to('Editer', [:edit, pet], class: "btn btn-primary btn-sm") %>
            <%= link_to('Supprimer', pet, class: "btn btn-danger btn-sm", data: {confirm: 'Etes vous sur ?', method: :delete}) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

<%= render template: 'layouts/profile' %>

app/views/pets/new.html.erb
<% content_for :content do %>
  <div class="card text-white bg-secondary">
    <h5 class="card-header">Ajouter un animal</h5>
    <div class="card-body">
      <%= render 'form', pet: @pet %>
    </div>
  </div>
<% end %>

<%= render template: 'layouts/profile' %>