config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  get '/profil', to: 'users#edit', as: :profil
  patch '/profil', to: 'users#update'
  get '/users', to: 'users#new'

  resources :users, only: [:new, :create] do
    member do
      get 'confirm'
    end
  end

  #Pets
  resources :pets

  #passwords
  resources :passwords, only: [:new, :create, :edit, :update]

  #sessions
  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :destroy_session

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petsy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <header class="p-1">
      <ul class="bg-dark nav align-items-center justify-content-start mb-lg-0">
        <div class="container-fluid">
          <li><a href="<%= root_path %>" class="navbar-brand">Petsy - Le réseau social</a></li>
        </div>
      </ul>
      <div class="d-flex bg-dark text-white flex-wrap align-items-center justify-content-end">
        <div class="container-fluid">
          <ul class="nav justify-content-end mb-lg-2">
            <% if user_signed_in %>
              <div class="dropdown">
                <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuLogin" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= current_user.login %>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLogin">
                  <li><%= link_to "Mon Profil", profil_path, class: "dropdown-item" %></li>
                  <li><%= link_to "Se déconnecter", destroy_session_path, class: "dropdown-item", data: {method: :delete} %></li>
                </ul>
              </div>
            <% else %>
              <li><a href="<%= users_path %>" class="nav-link px-2 text-white">S'inscrire</a></li>
              <li><a href="<%= new_session_path %>" class="nav-link px-2 text-white">Se connecter</a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>
    <div class="container-fluid">
      <div class="container-fluid" style="padding-top: 1rem;">
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name %>"><%= msg %></div>
        <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/profile.html.erb
<div class="row">
  <div class="col-md-8">
    <%= yield(:content) %>
  </div>
  <div class="col-md-4">
    <div class="list-group">
      <a href="<%= profil_path %>" class="list-group-item list-group-item-secondary <%= yield(:tag) == 'profiles' ? 'active' : '' %>">Mon profil</a>
      <a href="<%= pets_path %>" class="list-group-item list-group-item-secondary <%= yield(:tag) == 'pets' ? 'active' : '' %>">Mes animaux</a>
    </div>
  </div>
</div>